# Data Collection Settings
data:
  fastf1_cache_dir: "data/raw/fastf1_cache"
  seasons_to_collect: [2022, 2023, 2024]
  data_update_frequency: "daily"  # Options: daily, weekly, race_weekend

# Model Settings
model:
  tire_degradation:
    algorithm: "xgboost"
    features:
      - "lap_time"
      - "tire_age"
      - "fuel_load"
      - "track_temp"
      - "air_temp"
      - "humidity"
    hyperparameters:
      learning_rate: 0.1
      max_depth: 6
      n_estimators: 100

# Race Strategy Settings
strategy:
  min_pit_stop_time: 20  # seconds
  safety_margin: 1.5     # seconds
  tire_compounds:
    - "soft"
    - "medium"
    - "hard"
    - "intermediate"
    - "wet"

# Visualization Settings
visualization:
  theme: "dark"  # Options: light, dark
  plot_style: "seaborn"
  default_colors:
    - "#FF1E1E"  # Ferrari Red
    - "#00D2BE"  # Mercedes Silver
    - "#0600EF"  # Red Bull Blue
    - "#FF8700"  # McLaren Orange

# Logging Settings
logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file: "logs/pitgenius.log"

# API Settings
api:
  rate_limit: 100  # requests per minute
  timeout: 30      # seconds
