# XGBoost Model Parameters
xgboost:
  tire_degradation:
    objective: "reg:squarederror"
    max_depth: 6
    learning_rate: 0.1
    n_estimators: 100
    min_child_weight: 1
    subsample: 0.8
    colsample_bytree: 0.8
    seed: 42

# Neural Network Parameters
neural_network:
  race_position:
    architecture:
      - type: "dense"
        units: 128
        activation: "relu"
      - type: "dropout"
        rate: 0.2
      - type: "dense"
        units: 64
        activation: "relu"
      - type: "dense"
        units: 1
        activation: "linear"
    training:
      batch_size: 32
      epochs: 100
      validation_split: 0.2
      early_stopping_patience: 10

# Random Forest Parameters
random_forest:
  weather_impact:
    n_estimators: 100
    max_depth: 10
    min_samples_split: 2
    min_samples_leaf: 1
    max_features: "auto"
    random_state: 42

# Feature Engineering Parameters
feature_engineering:
  tire_age:
    max_age: 50  # laps
    degradation_curve: "exponential"
  
  track_position:
    sectors: 3
    normalize: true
  
  weather:
    temperature_range: [-10, 45]  # Celsius
    humidity_range: [0, 100]      # Percentage

# Model Evaluation Parameters
evaluation:
  metrics:
    - "mean_squared_error"
    - "mean_absolute_error"
    - "r2_score"
  
  cross_validation:
    n_splits: 5
    shuffle: true
    random_state: 42
