[theme]
primaryColor = "#FF1E1E"  # Ferrari Red
backgroundColor = "#0E1117"
secondaryBackgroundColor = "#262730"
textColor = "#FAFAFA"

[server]
maxUploadSize = 200
enableCORS = true

[browser]
gatherUsageStats = false 